src/Entity/Video.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VideoRepository")
 */
class Video
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=32, unique=true)
     */
    private $hash;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=180)
     */
    private $author_username;

    /**
     * @ORM\Column(type="datetime")
     */
    private $uploaded;

    /**
     * @ORM\Column(type="integer")
     */
    private $views;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $duration;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\VideoRate", mappedBy="video", orphanRemoval=true)
     */
    private $rates;

    /**
     * @ORM\OneToMany(
     *     targetEntity="App\Entity\Comment",
     *     mappedBy="video",
     *     orphanRemoval=true,
     *     cascade={"persist","remove"}
     *     )
     */
    private $comments;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default" : "0"})
     */
    private $price = 0;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Channel", inversedBy="videos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $channel;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="video")
     */
    private $categories;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Playlist", mappedBy="videos")
     */
    private $playlists;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isPublic = true;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="paidForVideos")
     */
    private $usersWithAccess;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $allowsAds;

    /**
     * @ORM\Column(type="boolean")
     */
    private $hasDemo;

    public function __construct()
    {
        $this->uploaded = new DateTimeImmutable();
        $this->views = 0;
        $this->description = '';
        $this->rates = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->categories = new ArrayCollection();
        $this->playlists = new ArrayCollection();
        $this->usersWithAccess = new ArrayCollection();
        $this->isPublic = true;
        $this->hasDemo = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getAuthorUsername(): ?string
    {
        return $this->author_username;
    }

    public function setAuthorUsername(string $author_username): self
    {
        $this->author_username = $author_username;

        return $this;
    }

    public function getUploaded(): ?DateTimeInterface
    {
        return $this->uploaded;
    }

    public function setUploaded(DateTimeInterface $uploaded): self
    {
        $this->uploaded = $uploaded;

        return $this;
    }

    public function getViews(): ?int
    {
        return $this->views;
    }

    public function setViews(int $views): self
    {
        $this->views = $views;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function toEncryptableArray()
    {
        return [
            'title' => $this->getTitle(),
            'author_username' => $this->getAuthorUsername(),
            'uploaded' => $this->getUploaded(),
            'duration' => $this->getDuration(),
        ];
    }

    public function generateHash()
    {
        $serialized = json_encode($this->toEncryptableArray());
        $hash = md5($serialized);
        $this->setHash($hash);

        return $hash;
    }

    /**
     * @return Collection|VideoRate[]
     */
    public function getRates(): Collection
    {
        return $this->rates;
    }

    public function addRate(VideoRate $rate): self
    {
        if (!$this->rates->contains($rate)) {
            $rate->setVideo($this);
            $this->rates[] = $rate;
        }

        return $this;
    }

    public function removeRate(VideoRate $rate): self
    {
        if ($this->rates->contains($rate)) {
            $this->rates->removeElement($rate);
            if ($rate->getVideo() === $this) {
                $rate->setVideo(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $comment->setVideo($this);
            $this->comments[] = $comment;
        }

        return $this;
    }

    public function comment(string $message, User $user): self
    {
        $comment = (new Comment())
            ->setContents($message)
            ->setAuthorUsername($user->getUsername())
            ->setAuthor($user);

        $this->addComment($comment);

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getVideo() === $this) {
                $comment->setVideo(null);
            }
        }

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getPriceAsCurrency(): ?float
    {
        return $this->price/100;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getChannel(): ?Channel
    {
        return $this->channel;
    }

    public function setChannel(?Channel $channel): self
    {
        $this->channel = $channel;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->addVideo($this);
        }

        return $this;
    }

//    /**
//     * @param Collection $categories
//     */
//    public function setCategories(Collection $categories): self
//    {
//        $this->categories = $categories;
//
//        return $this;
//    }

    public function setCategories(Collection $categories)
    {
        $this->categories = $categories;

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
            $category->removeVideo($this);
        }

        return $this;
    }

    /**
     * @return Collection|Playlist[]
     */
    public function getPlaylists(): Collection
    {
        return $this->playlists;
    }

    public function addPlaylist(Playlist $playlist): self
    {
        if (!$this->playlists->contains($playlist)) {
            $this->playlists[] = $playlist;
            $playlist->addVideo($this);
        }

        return $this;
    }

    public function removePlaylist(Playlist $playlist): self
    {
        if ($this->playlists->contains($playlist)) {
            $this->playlists->removeElement($playlist);
            $playlist->removeVideo($this);
        }

        return $this;
    }

    public function getDurationInReadableFormat(): string
    {
        if (!$this->duration) {
            return '';
        }
        $format = $this->duration >= 60*60 ? 'h:i:s' : 'i:s';

        return date($format, $this->duration);
    }

    public function getIsPublic(): ?bool
    {
        return $this->isPublic;
    }

    public function setIsPublic(?bool $isPublic): self
    {
        $this->isPublic = $isPublic;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsersWithAccess(): Collection
    {
        return $this->usersWithAccess;
    }

    public function addUsersWithAccess(User $usersWithAccess): self
    {
        if (!$this->usersWithAccess->contains($usersWithAccess)) {
            $this->usersWithAccess[] = $usersWithAccess;
        }

        return $this;
    }

    public function removeUsersWithAccess(User $usersWithAccess): self
    {
        if ($this->usersWithAccess->contains($usersWithAccess)) {
            $this->usersWithAccess->removeElement($usersWithAccess);
        }

        return $this;
    }

    public function getAllowsAds(): ?bool
    {
        return $this->allowsAds;
    }

    public function setAllowsAds(?bool $allowsAds): self
    {

templates/video/_video_card.html.twig
<div class="video-thumb mb-3">
    <a href="{{ path('app_video_watch', {video_hash: video.hash}) }}"
       class="w-100 text-dark{% if video.price > 0 %} bootbox-dialog-button{% endif %}"
            {% if video.price > 0 %}
        data-title="Film jest płatny ({{ video.priceAsCurrency }}zł). Jeżeli nie masz obecnie do niego dostępu - środki zostaną pobrane z Twojego portfela. Kontynuować?"
        data-secondaryurl="{{ path('app_video_watch_demo', {video_hash: video.hash}) }}"
            {% endif %}>
        <img class="w-100" src="{{ asset( [uploads_dir, '/thumbs/', video.hash, '.jpg']|join ) }}"> <br>
        <div class="video-card-title">{{ video.title|slice(0, 55) }}{% if video.title|length > 55 %}...{% endif %}</div>
    </a>
    {% if video.price > 0 %}
        <i class="fas fa-dollar-sign text-success"
           data-toggle="tooltip"
           data-placement="top"
           title="Materiał płatny - {{ video.priceAsCurrency }} PLN"></i>
    {% endif %}
    {% if video.hasDemo %}
        <a style="float:right" href="{{ path('app_video_watch_demo', {'video_hash':video.hash}) }}">
            <i class="fas fa-caret-square-up text-info"
               data-toggle="tooltip"
               data-placement="top"
               title="Obejrzyj demo"></i>
        </a>
    {% endif %}
    {% if app.user is not null %}
        {% if video.channel.id is same as(app.user.channel.id) %}
            <a style="float:right" href="{{ path('app_video_remove', {'video_hash':video.hash}) }}">
                <i class="fas fa-times text-danger"
                   data-toggle="tooltip"
                   data-placement="top"
                   title="Usuń film"></i>
            </a>
            <a style="float:right" href="{{ path('app_video_edit', {'video_hash':video.hash}) }}">
                <i class="fas fa-edit text-primary"
                   data-toggle="tooltip"
                   data-placement="top"
                   title="Edytuj film"></i>
            </a>
        {% endif %}
        {% set playlist = isVideoInUserPlaylists(video, app.user) %}
        {% if playlist is not null %}
            <a class="ml-1 mr-1"
               style="float:right"
               href="{{ path('app_video_remove_from_playlist', {'video_hash':video.hash, 'playlist':playlist.id}) }}">
                <i class="fas fa-times text-warning"
                   data-toggle="tooltip"
                   data-placement="top"
                   title="Usuń film z playlisty"></i>
            </a>
        {% endif %}
        {% if app.user is not null and playlist is null %}
            <a class="ml-1 mr-1"
               style="float:right"
               href="{{ path('app_video_add_to_playlist', {'video_hash':video.hash}) }}">
                <i class="fas fa-plus text-success"
                   data-toggle="tooltip"
                   data-placement="top"
                   title="Dodaj do playlisty"></i>
            </a>
        {% endif %}
    {% endif %}
</div>

templates/video/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
    <div class="container">
        <div class="form-container row pt-5">

            <form id="uploadForm" class="w-100" action="{{ path('app_video_add') }}" method="post" enctype="multipart/form-data" data-success="{{ path(success_route) }}">
                <div class="input-group pb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Tytuł filmu</span>
                    </div>
                    <input class="form-control" type="text" id="videoTitle" name="add_video[title]">
                </div>
                <div class="form-group">
                    <label for="exampleFormControlTextarea1">Opis</label>
                    <textarea class="form-control" id="videoDescription" name="add_video[description]" rows="3"></textarea>
                </div>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Plik wideo</span>
                    </div>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="videoFile" name="add_video[file]">
                        <label class="custom-file-label" for="file">Wybierz plik</label>
                    </div>
                </div>
                <div class="input-group mt-2 pb-2">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Miniatura</span>
                    </div>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="videoThumbnail" name="add_video[thumbnail]">
                        <label class="custom-file-label" for="thumbnail">Wybierz plik</label>
                    </div>
                </div>
                <div class="progress mt-2">
                    <div
                            id="upload-progress"
                            class="progress-bar progress-bar-striped progress-bar-animated bg-info"
                            role="progressbar"
                            style="width: 0%"
                            aria-valuenow="50"
                            aria-valuemin="0"
                            aria-valuemax="100"
                            data-progress="0"
                    ></div>
                </div>
                <div class="row pt-3">
                    <input class="btn btn-primary w-100" type="submit" name="add_video[submit]" value="Wyślij">
                </div>
                <input type="hidden" name="add_video[_token]" id="csrfToken" value="{{ csrf_token('add_video') }}">
            </form>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/video_upload.js') }}"></script>
{% endblock %}

templates/video/add_to_playlist.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
    <div class="container">
        {{ form_start(form) }}
        {{ form_row(form.playlist) }}
        <button class="btn btn-success" type="submit">Zapisz</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/video/add_v2.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
    <div class="container">
        <div class="form-container row pt-5">
            <a class="btn btn-success" href="{{ path('app_category_new') }}">Dodaj kategorię</a>
            {{ form_start(form, {'attr': {
                'id': 'uploadForm',
                'data-success': path(success_route, {'channel_name':app.user.channel.name})
            }}) }}
                {{ form_row(form.title) }}
                {{ form_row(form.description) }}
                {{ form_row(form.file) }}
                {{ form_row(form.thumbnail) }}
                {{ form_row(form.price) }}
                {{ form_row(form.categories) }}
                {{ form_row(form.watermark) }}
                {{ form_row(form.isPublic) }}
                <div class="progress mt-2">
                    <div
                            id="upload_progress"
                            class="progress-bar progress-bar-striped progress-bar-animated bg-info"
                            role="progressbar"
                            style="width: 0%"
                            aria-valuenow="50"
                            aria-valuemin="0"
                            aria-valuemax="100"
                            data-progress="0"
                    ></div>
                </div>
                {{ form_row(form.submit) }}
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/video_upload.js') }}"></script>
    <script src="{{ asset('js/fileUpload.js') }}"></script>
{% endblock %}

templates/video/demo.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ video.title }} - Demo{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/video_watch.css') }}">
    <link rel="stylesheet" href="{{ asset('css/demo_watch.css') }}">
{% endblock %}

{% block body %}
    <style>
        .example-wrapper {
            margin: 1em auto;
            max-width: 800px;
            width: 95%;
            font: 18px/1.5 sans-serif;
        }

        .example-wrapper code {
            background: #F5F5F5;
            padding: 2px 6px;
        }

        .com-author {
            font-size: 15px;
        }

        .info-panel {
            font-size: 25px;
        }

        .info-panel button {
            font-size: 25px;
        }

        .avatar {
            width: 60px;
            height: 60px;
        }

        .user-card {
            width: 100px;
        }

        .com-date {
            font-size: 14px;
        }

        .sub-avatar {
            width: 45px;
            height: 45px;
        }

        .sub-user-card {
            width: 60px;
        }

        .sub-com-date {
            font-size: 12px;
        }

        .sub-content {
            font-size: 15px;
            min-height: 32px;
        }

        .sub-com-author {
            font-size: 13px;
        }
    </style>

    <div class="example-wrapper">

        <div class="container text-dark">
            <div class="row">
                <div class="col-12">
                    {% if video.allowsAds is same as(true) and ad is not null %}
                        Reklama:<br>
                        <div class="video-ad-{{ ad.content }}">
                            <img width="200px" src="{{ asset( [uploads_dir, '/advertisements/', ad.content, '.jpg']|join ) }}" alt="ad-content"> <br>
                        </div>
                    {% endif %}
                    <div class="h3 my-3 w-100">
                        {{ video.title }}
                        {% if app.user is not null %}
                            {% if app.user == video.channel.user %}
                                <a style="float:right" href="{{ path('app_video_edit', {'video_hash':video.hash}) }}">
                                    <i class="fas fa-edit text-primary"
                                       data-toggle="tooltip"
                                       data-placement="top"
                                       title="Edytuj film"></i>
                                </a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
                <div class="col text-right">
                    {% if video.categories is not empty %}
                        <div>
                            {% for category in video.categories %}
                                <a href="{{ path('app_category_show',{'id':category.id}) }}">#{{ category.name }},</a>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="container p-1 w-100 d-flex justify-content-between">
                {% if video.channel is not null %}
                    <a href="{{ path('app_user_channel',{'channel_name':video.channel.name}) }}"
                       class="text-dark">{{ video.channel.name }}</a>
                {% endif %}
                <div class="vid-data">{{ video.uploaded|date("d-m-Y") }}</div>
            </div>
            <div class="player-wrapper">
                <video id="player" class="demo-player embed-responsive embed-responsive-16by9" autoplay controls
                       data-video-hash="{{ video.hash }}">
                    <source src="{{ asset([uploads_dir, '/demos/', video.hash, '.mp4']|join) }}" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
                <div class="demo-overlay d-none">
                </div>
                <div class="demo-buy d-none">
                    <h1>To jest wersja demonstracyjna filmu</h1>
                    <h2>Aby uzyskać dostęp do pełnej wersji zakup film</h2>
                    <a href="{{ path('app_video_watch', {video_hash: video.hash}) }}"
                       class="text-dark{% if video.price > 0 %} bootbox-confirm-button{% endif %}"
                            {% if video.price > 0 %}
                        data-title="Film jest płatny ({{ video.priceAsCurrency }}zł). Jeżeli nie masz obecnie do niego dostępu - środki zostaną pobrane z Twojego portfela. Kontynuować?"
                            {% endif %}>
                        <input class="btn btn-info" type="button" value="Kup film">
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/demo_player.js') }}"></script>
{% endblock %}

templates/video/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edycja filmu{% endblock %}

{% block body %}
<div class="container">
    {{ form(form) }}
</div>
{% endblock %}

templates/video/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ video.title }} - Playing{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/video_watch.css') }}">
{% endblock %}

{% block body %}
    <style>
        .example-wrapper {
            margin: 1em auto;
            max-width: 800px;
            width: 95%;
            font: 18px/1.5 sans-serif;
        }

        .example-wrapper code {
            background: #F5F5F5;
            padding: 2px 6px;
        }

        .com-author {
            font-size: 15px;
        }

        .info-panel {
            font-size: 25px;
        }

        .info-panel button {
            font-size: 25px;
        }

        .avatar {
            width: 60px;
            height: 60px;
        }

        .user-card {
            width: 100px;
        }

        .com-date {
            font-size: 14px;
        }

        .sub-avatar {
            width: 45px;
            height: 45px;
        }

        .sub-user-card {
            width: 60px;
        }

        .sub-com-date {
            font-size: 12px;
        }

        .sub-content {
            font-size: 15px;
            min-height: 32px;
        }

        .sub-com-author {
            font-size: 13px;
        }
    </style>

    <div class="example-wrapper">

        <div class="container text-dark">
            <div class="row">
                <div class="col-12">
                    {% if video.allowsAds is same as(true) and ad is not null %}
                        Reklama:<br>
                        <div class="video-ad-{{ ad.content }}">
                            <img width="200px" src="{{ asset( [uploads_dir, '/advertisements/', ad.content, '.jpg']|join ) }}" alt="ad-content"> <br>
                        </div>
                    {% endif %}
                    <div class="h3 my-3 w-100">
                        {{ video.title }}
                        {% if app.user is not null %}
                            {% if app.user == video.channel.user %}
                                <a style="float:right" href="{{ path('app_video_edit', {'video_hash':video.hash}) }}">
                                    <i class="fas fa-edit text-primary"
                                       data-toggle="tooltip"
                                       data-placement="top"
                                       title="Edytuj film"></i>
                                </a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
                <div class="col text-right">
                    {% if video.categories is not empty %}
                        <div>
                            {% for category in video.categories %}
                                <a href="{{ path('app_category_show',{'id':category.id}) }}">#{{ category.name }},</a>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="container p-1 w-100 d-flex justify-content-between">
                {% if video.channel is not null %}
                    <a href="{{ path('app_user_channel',{'channel_name':video.channel.name}) }}"
                       class="text-dark">{{ video.channel.name }}</a>
                {% endif %}
                <div class="vid-data">{{ video.uploaded|date("d-m-Y") }}</div>
            </div>
            <video id="player" class="embed-responsive embed-responsive-16by9" autoplay controls
                   data-video-hash="{{ video.hash }}">
                <source src="{{ asset([uploads_dir, '/', video.hash, '.mp4']|join) }}" type="video/mp4">
                Your browser does not support the video tag.
            </video>
            <div class="info-panel container p-2 w-100 d-flex justify-content-between">
                <div id="thumbs-container" data-action="{{ path('app_video_rate', {video_hash:video.hash}) }}">
                    <button class="btn btn-light px-4" id="like_btn">
                        {% if user_rate is defined and user_rate is not null and user_rate == 1 %}
                            <i class="fas fa-thumbs-up text-dark"></i>
                        {% else %}
                            <i class="far fa-thumbs-up text-dark"></i>
                        {% endif %}
                        <span id="thumbs_up" class="text-dark">{{ thumbs_up }}</span>
                    </button>
                    <button class="btn btn-light px-4" id="dislike_btn">
                        {% if user_rate is defined and user_rate is not null and user_rate == 0 %}
                            <i class="fas fa-thumbs-down text-dark"></i>
                        {% else %}
                            <i class="far fa-thumbs-down text-dark"></i>
                        {% endif %}
                        <span id="thumbs_down" class="text-dark">{{ thumbs_down }}</span>
                    </button>
                </div>
                <div class="views">
                    <i class="fas fa-eye"></i> {{ video.views }}
                </div>
            </div>
            <div class="my-3">
                <h5>Comments: </h5>
                {% for comment in comments %}
                    {{ include('video/comment/_comment.html.twig') }}
                {% endfor %}
                {{ include('video/comment/_comment_reply.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/video_rate.js') }}"></script>
    <script src="{{ asset('js/comment_reply.js') }}"></script>
    <script src="{{ asset('js/comment_edit.js') }}"></script>
{% endblock %}